### ISSUE TITLE
RestClientBuilder doesn't allow AutoCloseable extension of client interface with a type level URI template

### ISSUE THREAD

**Issue by StaffanHorke** [resteasy/resteasy-microprofile#147]
The RestClientBuilder throws a RestClientDefinitionException when building from a client interface that extends AutoCloseable and has a URI template on the type level. The Exceptions says `Rest client failed: org.eclipse.microprofile.rest.client.RestClientDefinitionException: Parameters and variables don't match on interface on interface Foo::close`.

The specification says that the client interface is allowed to extend AutoCloseable. The implementation doesn't allow the unresolved URI template of the close method.

**Comment by jamezp** [comment]
What version of RESTEasy MicroProfile Client are you using? Please note that my replies may be delayed this week as I'm going to be in meetings all this coming week.

**Comment by StaffanHorke** [comment]
Sorry, I should have included that. I'm using Wildfly 27.0.0.Final and it says resteasy-client-microprofile-2.0.0.Final.

I've written a test case that illustrates the issue, you can find it here: [AutoCloseableClient.java](https://github.com/StaffanHorke/resteasy-microprofile/blob/issue147/rest-client/src/test/java/org/jboss/resteasy/microprofile/client/AutoCloseableClientTest.java).
