### ISSUE TITLE
Error occurred while reading SSEsjava.lang.IllegalStateException: RESTEASY004087: No suitable message body reader for class : jakarta.ws.rs.core.GenericType

### ISSUE THREAD

**Issue by emweber** [resteasy/resteasy-microprofile#215]
thrown in SSEPublisher#pump() when REST resource method return type is not Publisher<**String**>.
In my case, the method signature is
```
@GET
  // the following give media type text/event-stream;element-type="application/json"
  @Produces("text/event-stream")
  @org.jboss.resteasy.annotations.SseElementType(MediaType.APPLICATION_JSON)

  // the following gives media type application/x-stream-general;element-type="application/json"
//  @org.jboss.resteasy.annotations.Stream
  Publisher<SseEventDto> getEvents();
```

SSEPublisher calls `event.readData((Class) typeArgument)` which tries to lookup a message bodyx reader for type MediaType.TEXT_PLAIN_TYPE.
SSEPublisher should call  `event.readData((Class) typeArgument, MediaType.APPLICATION_JSON)` in this case to get the proper reader.

Here is how resteasy-rxjava2 handle this: [e.readData(clazz, ((InboundSseEventImpl) e).getMediaType())](https://github.com/resteasy/resteasy/blob/5887d83d0617843a94914b8f79f3db107d2a76e9/resteasy-rxjava2/src/main/java/org/jboss/resteasy/rxjava2/FlowableRxInvokerImpl.java#L187)

**Comment by jamezp** [comment]
I apologize for the very late reply here. I'm not sure how I missed this. Do you have a reproducer by chance? I'm not sure I follow as this seems more like a https://github.com/resteasy/resteasy issue.

**Comment by jamezp** [comment]
Excellent, thank you @emweber. I see the problem now. The `MediaType` is not being used when reading the event so it's always reading as `text/plain`.
