### ISSUE TITLE
Resteasy microprofile client does not create specific WebApplicationException

### ISSUE THREAD

**Issue by chonton** [resteasy/resteasy-microprofile#373]
**The bug**
When a rest api returns a 4xx or 5xx status code, Resteasy microprofile client creates a generic WebApplicationException.
I must register the following ResponseExceptionMapper<RuntimeException> to get the expected behavior.

**Expected behavior**
Produce a specific WebApplicationException such as ForbiddenException for 403 or NotFoundException for 404. This is the behavior of classic Resteasy client.

**Actual behavior**
Resteasy microprofile client creates a generic WebApplicationException with the correct status code.

**How to Reproduce?**
Invoke any web service that returns a 4xx or 5xx status code

This is root cause of [quarkus #23951](https://github.com/quarkusio/quarkus/issues/23951)

**Comment by jamezp** [comment]
I'll think about this more, but I guess it depends on how you interpret https://download.eclipse.org/microprofile/microprofile-rest-client-4.0/microprofile-rest-client-spec-4.0.html#_default_responseexceptionmapper

> Each implementation will provide out of the box a ResponseExceptionMapper implementation that will map the response into a WebApplicationException whenever the response status code is >= 400.

**Comment by chonton** [comment]
@jamezp have you thought about this?  What's the least surprise for developers migrating from Resteasy?
